// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package payment

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentProvider is an autogenerated mock type for the PaymentProvider type
type MockPaymentProvider struct {
	mock.Mock
}

type MockPaymentProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentProvider) EXPECT() *MockPaymentProvider_Expecter {
	return &MockPaymentProvider_Expecter{mock: &_m.Mock}
}

// ProcessPayment provides a mock function with given fields: ctx, token, planID
func (_m *MockPaymentProvider) ProcessPayment(ctx context.Context, token string, planID string) (string, error) {
	ret := _m.Called(ctx, token, planID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, token, planID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, token, planID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, planID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentProvider_ProcessPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessPayment'
type MockPaymentProvider_ProcessPayment_Call struct {
	*mock.Call
}

// ProcessPayment is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - planID string
func (_e *MockPaymentProvider_Expecter) ProcessPayment(ctx interface{}, token interface{}, planID interface{}) *MockPaymentProvider_ProcessPayment_Call {
	return &MockPaymentProvider_ProcessPayment_Call{Call: _e.mock.On("ProcessPayment", ctx, token, planID)}
}

func (_c *MockPaymentProvider_ProcessPayment_Call) Run(run func(ctx context.Context, token string, planID string)) *MockPaymentProvider_ProcessPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockPaymentProvider_ProcessPayment_Call) Return(_a0 string, _a1 error) *MockPaymentProvider_ProcessPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentProvider_ProcessPayment_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockPaymentProvider_ProcessPayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentProvider creates a new instance of MockPaymentProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentProvider {
	mock := &MockPaymentProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
