// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package ai

import (
	context "context"

	ai "github.com/JosemaPereira/TrAIveler/backend/internal/ai"

	mock "github.com/stretchr/testify/mock"
)

// MockAIClient is an autogenerated mock type for the AIClient type
type MockAIClient struct {
	mock.Mock
}

type MockAIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIClient) EXPECT() *MockAIClient_Expecter {
	return &MockAIClient_Expecter{mock: &_m.Mock}
}

// GenerateItinerary provides a mock function with given fields: ctx, req
func (_m *MockAIClient) GenerateItinerary(ctx context.Context, req ai.ItineraryRequest) (*ai.ItineraryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateItinerary")
	}

	var r0 *ai.ItineraryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ai.ItineraryRequest) (*ai.ItineraryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ai.ItineraryRequest) *ai.ItineraryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ai.ItineraryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ai.ItineraryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAIClient_GenerateItinerary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateItinerary'
type MockAIClient_GenerateItinerary_Call struct {
	*mock.Call
}

// GenerateItinerary is a helper method to define mock.On call
//   - ctx context.Context
//   - req ai.ItineraryRequest
func (_e *MockAIClient_Expecter) GenerateItinerary(ctx interface{}, req interface{}) *MockAIClient_GenerateItinerary_Call {
	return &MockAIClient_GenerateItinerary_Call{Call: _e.mock.On("GenerateItinerary", ctx, req)}
}

func (_c *MockAIClient_GenerateItinerary_Call) Run(run func(ctx context.Context, req ai.ItineraryRequest)) *MockAIClient_GenerateItinerary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ai.ItineraryRequest))
	})
	return _c
}

func (_c *MockAIClient_GenerateItinerary_Call) Return(_a0 *ai.ItineraryResponse, _a1 error) *MockAIClient_GenerateItinerary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIClient_GenerateItinerary_Call) RunAndReturn(run func(context.Context, ai.ItineraryRequest) (*ai.ItineraryResponse, error)) *MockAIClient_GenerateItinerary_Call {
	_c.Call.Return(run)
	return _c
}

// StreamItinerary provides a mock function with given fields: ctx, req
func (_m *MockAIClient) StreamItinerary(ctx context.Context, req ai.ItineraryRequest) (<-chan ai.StreamChunk, <-chan error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StreamItinerary")
	}

	var r0 <-chan ai.StreamChunk
	var r1 <-chan error
	if rf, ok := ret.Get(0).(func(context.Context, ai.ItineraryRequest) (<-chan ai.StreamChunk, <-chan error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ai.ItineraryRequest) <-chan ai.StreamChunk); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan ai.StreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ai.ItineraryRequest) <-chan error); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}

// MockAIClient_StreamItinerary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamItinerary'
type MockAIClient_StreamItinerary_Call struct {
	*mock.Call
}

// StreamItinerary is a helper method to define mock.On call
//   - ctx context.Context
//   - req ai.ItineraryRequest
func (_e *MockAIClient_Expecter) StreamItinerary(ctx interface{}, req interface{}) *MockAIClient_StreamItinerary_Call {
	return &MockAIClient_StreamItinerary_Call{Call: _e.mock.On("StreamItinerary", ctx, req)}
}

func (_c *MockAIClient_StreamItinerary_Call) Run(run func(ctx context.Context, req ai.ItineraryRequest)) *MockAIClient_StreamItinerary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ai.ItineraryRequest))
	})
	return _c
}

func (_c *MockAIClient_StreamItinerary_Call) Return(_a0 <-chan ai.StreamChunk, _a1 <-chan error) *MockAIClient_StreamItinerary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAIClient_StreamItinerary_Call) RunAndReturn(run func(context.Context, ai.ItineraryRequest) (<-chan ai.StreamChunk, <-chan error)) *MockAIClient_StreamItinerary_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAIClient creates a new instance of MockAIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIClient {
	mock := &MockAIClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
