// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package example

import (
	context "context"

	example "github.com/JosemaPereira/TrAIveler/backend/internal/example"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateExample provides a mock function with given fields: ctx, input
func (_m *MockService) CreateExample(ctx context.Context, input example.CreateInput) (*example.Example, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateExample")
	}

	var r0 *example.Example
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, example.CreateInput) (*example.Example, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, example.CreateInput) *example.Example); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.Example)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, example.CreateInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExample'
type MockService_CreateExample_Call struct {
	*mock.Call
}

// CreateExample is a helper method to define mock.On call
//   - ctx context.Context
//   - input example.CreateInput
func (_e *MockService_Expecter) CreateExample(ctx interface{}, input interface{}) *MockService_CreateExample_Call {
	return &MockService_CreateExample_Call{Call: _e.mock.On("CreateExample", ctx, input)}
}

func (_c *MockService_CreateExample_Call) Run(run func(ctx context.Context, input example.CreateInput)) *MockService_CreateExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(example.CreateInput))
	})
	return _c
}

func (_c *MockService_CreateExample_Call) Return(_a0 *example.Example, _a1 error) *MockService_CreateExample_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateExample_Call) RunAndReturn(run func(context.Context, example.CreateInput) (*example.Example, error)) *MockService_CreateExample_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExample provides a mock function with given fields: ctx, id
func (_m *MockService) DeleteExample(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExample")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExample'
type MockService_DeleteExample_Call struct {
	*mock.Call
}

// DeleteExample is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteExample(ctx interface{}, id interface{}) *MockService_DeleteExample_Call {
	return &MockService_DeleteExample_Call{Call: _e.mock.On("DeleteExample", ctx, id)}
}

func (_c *MockService_DeleteExample_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteExample_Call) Return(_a0 error) *MockService_DeleteExample_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteExample_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteExample_Call {
	_c.Call.Return(run)
	return _c
}

// GetExample provides a mock function with given fields: ctx, id
func (_m *MockService) GetExample(ctx context.Context, id string) (*example.Example, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetExample")
	}

	var r0 *example.Example
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*example.Example, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *example.Example); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.Example)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExample'
type MockService_GetExample_Call struct {
	*mock.Call
}

// GetExample is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) GetExample(ctx interface{}, id interface{}) *MockService_GetExample_Call {
	return &MockService_GetExample_Call{Call: _e.mock.On("GetExample", ctx, id)}
}

func (_c *MockService_GetExample_Call) Run(run func(ctx context.Context, id string)) *MockService_GetExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetExample_Call) Return(_a0 *example.Example, _a1 error) *MockService_GetExample_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetExample_Call) RunAndReturn(run func(context.Context, string) (*example.Example, error)) *MockService_GetExample_Call {
	_c.Call.Return(run)
	return _c
}

// ListExamples provides a mock function with given fields: ctx, filters
func (_m *MockService) ListExamples(ctx context.Context, filters example.ListFilters) (*example.ListOutput, error) {
	ret := _m.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for ListExamples")
	}

	var r0 *example.ListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, example.ListFilters) (*example.ListOutput, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, example.ListFilters) *example.ListOutput); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.ListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, example.ListFilters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListExamples_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExamples'
type MockService_ListExamples_Call struct {
	*mock.Call
}

// ListExamples is a helper method to define mock.On call
//   - ctx context.Context
//   - filters example.ListFilters
func (_e *MockService_Expecter) ListExamples(ctx interface{}, filters interface{}) *MockService_ListExamples_Call {
	return &MockService_ListExamples_Call{Call: _e.mock.On("ListExamples", ctx, filters)}
}

func (_c *MockService_ListExamples_Call) Run(run func(ctx context.Context, filters example.ListFilters)) *MockService_ListExamples_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(example.ListFilters))
	})
	return _c
}

func (_c *MockService_ListExamples_Call) Return(_a0 *example.ListOutput, _a1 error) *MockService_ListExamples_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListExamples_Call) RunAndReturn(run func(context.Context, example.ListFilters) (*example.ListOutput, error)) *MockService_ListExamples_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExample provides a mock function with given fields: ctx, id, expectedVersion, input
func (_m *MockService) UpdateExample(ctx context.Context, id string, expectedVersion int, input example.UpdateInput) (*example.Example, error) {
	ret := _m.Called(ctx, id, expectedVersion, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExample")
	}

	var r0 *example.Example
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, example.UpdateInput) (*example.Example, error)); ok {
		return rf(ctx, id, expectedVersion, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, example.UpdateInput) *example.Example); ok {
		r0 = rf(ctx, id, expectedVersion, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.Example)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, example.UpdateInput) error); ok {
		r1 = rf(ctx, id, expectedVersion, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExample'
type MockService_UpdateExample_Call struct {
	*mock.Call
}

// UpdateExample is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - expectedVersion int
//   - input example.UpdateInput
func (_e *MockService_Expecter) UpdateExample(ctx interface{}, id interface{}, expectedVersion interface{}, input interface{}) *MockService_UpdateExample_Call {
	return &MockService_UpdateExample_Call{Call: _e.mock.On("UpdateExample", ctx, id, expectedVersion, input)}
}

func (_c *MockService_UpdateExample_Call) Run(run func(ctx context.Context, id string, expectedVersion int, input example.UpdateInput)) *MockService_UpdateExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(example.UpdateInput))
	})
	return _c
}

func (_c *MockService_UpdateExample_Call) Return(_a0 *example.Example, _a1 error) *MockService_UpdateExample_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateExample_Call) RunAndReturn(run func(context.Context, string, int, example.UpdateInput) (*example.Example, error)) *MockService_UpdateExample_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
