# RDS PostgreSQL Module
#
# Creates a single RDS PostgreSQL instance on private subnets, a security
# group that only accepts traffic from the ECS service on the Postgres
# port, and a Secrets Manager secret holding the generated master
# credentials.
#
# engine_version is deliberately pinned to 15.4 to match the postgres:15.4-
# alpine image used in docker-compose.yml and backend CI (see
# docs/architecture.md, docs/cloud-and-environments.md, docs/data-model.md).
# Do not bump this independently of that documented decision.

# ---------------------------------------------------------------------------
# Subnet group
# ---------------------------------------------------------------------------

resource "aws_db_subnet_group" "main" {
  name       = "${var.environment}-rds-subnet-group"
  subnet_ids = var.private_subnet_ids

  tags = {
    Name        = "${var.environment}-rds-subnet-group"
    Environment = var.environment
    ManagedBy   = "terraform"
    Project     = "traveler"
  }
}

# ---------------------------------------------------------------------------
# Security group
#
# Ingress is restricted to the ECS service's security group on port 5432
# only — no 0.0.0.0/0 ingress is permitted on this SG.
# ---------------------------------------------------------------------------

resource "aws_security_group" "rds" {
  name        = "${var.environment}-rds-sg"
  description = "Allow inbound PostgreSQL traffic from the ECS service only"
  vpc_id      = var.vpc_id

  ingress {
    description     = "PostgreSQL from ECS service"
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [var.ecs_security_group_id]
  }

  egress {
    description = "All outbound traffic"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name        = "${var.environment}-rds-sg"
    Environment = var.environment
    ManagedBy   = "terraform"
    Project     = "traveler"
  }
}

# ---------------------------------------------------------------------------
# Credentials (Secrets Manager)
#
# The master password is generated by the random provider — never a
# literal string — and stored in Secrets Manager alongside the username.
# ---------------------------------------------------------------------------

resource "random_password" "db_password" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name        = "traveler-${var.environment}-db-credentials"
  description = "RDS PostgreSQL master credentials for the ${var.environment} environment"

  tags = {
    Name        = "${var.environment}-db-credentials"
    Environment = var.environment
    ManagedBy   = "terraform"
    Project     = "traveler"
  }
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id

  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_password.result
  })
}

# ---------------------------------------------------------------------------
# RDS instance
# ---------------------------------------------------------------------------

resource "aws_db_instance" "main" {
  identifier     = "${var.environment}-traveler-db"
  engine         = "postgres"
  engine_version = "15.4"

  instance_class    = var.instance_class
  allocated_storage = 20

  db_name  = var.db_name
  username = var.db_username
  password = random_password.db_password.result

  multi_az                = var.multi_az
  backup_retention_period = var.backup_retention_days
  backup_window           = "03:00-04:00"
  maintenance_window      = "sun:04:00-sun:05:00"

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.rds.id]

  tags = {
    Name        = "${var.environment}-rds"
    Environment = var.environment
    ManagedBy   = "terraform"
    Project     = "traveler"
  }
}
