// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package trip

import (
	context "context"

	trip "github.com/JosemaPereira/TrAIveler/backend/internal/trip"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, role, title, description
func (_m *MockManager) Create(ctx context.Context, userID string, role string, title string, description *string) (*trip.Trip, error) {
	ret := _m.Called(ctx, userID, role, title, description)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (*trip.Trip, error)); ok {
		return rf(ctx, userID, role, title, description)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, *string) *trip.Trip); ok {
		r0 = rf(ctx, userID, role, title, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = rf(ctx, userID, role, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockManager_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - role string
//   - title string
//   - description *string
func (_e *MockManager_Expecter) Create(ctx interface{}, userID interface{}, role interface{}, title interface{}, description interface{}) *MockManager_Create_Call {
	return &MockManager_Create_Call{Call: _e.mock.On("Create", ctx, userID, role, title, description)}
}

func (_c *MockManager_Create_Call) Run(run func(ctx context.Context, userID string, role string, title string, description *string)) *MockManager_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(*string))
	})
	return _c
}

func (_c *MockManager_Create_Call) Return(_a0 *trip.Trip, _a1 error) *MockManager_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Create_Call) RunAndReturn(run func(context.Context, string, string, string, *string) (*trip.Trip, error)) *MockManager_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, tripID
func (_m *MockManager) Delete(ctx context.Context, userID string, tripID string) error {
	ret := _m.Called(ctx, userID, tripID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, tripID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tripID string
func (_e *MockManager_Expecter) Delete(ctx interface{}, userID interface{}, tripID interface{}) *MockManager_Delete_Call {
	return &MockManager_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, tripID)}
}

func (_c *MockManager_Delete_Call) Run(run func(ctx context.Context, userID string, tripID string)) *MockManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockManager_Delete_Call) Return(_a0 error) *MockManager_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_Delete_Call) RunAndReturn(run func(context.Context, string, string) error) *MockManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, userID, tripID
func (_m *MockManager) Get(ctx context.Context, userID string, tripID string) (*trip.Trip, error) {
	ret := _m.Called(ctx, userID, tripID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*trip.Trip, error)); ok {
		return rf(ctx, userID, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *trip.Trip); ok {
		r0 = rf(ctx, userID, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tripID string
func (_e *MockManager_Expecter) Get(ctx interface{}, userID interface{}, tripID interface{}) *MockManager_Get_Call {
	return &MockManager_Get_Call{Call: _e.mock.On("Get", ctx, userID, tripID)}
}

func (_c *MockManager_Get_Call) Run(run func(ctx context.Context, userID string, tripID string)) *MockManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockManager_Get_Call) Return(_a0 *trip.Trip, _a1 error) *MockManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Get_Call) RunAndReturn(run func(context.Context, string, string) (*trip.Trip, error)) *MockManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetItinerary provides a mock function with given fields: ctx, userID, tripID
func (_m *MockManager) GetItinerary(ctx context.Context, userID string, tripID string) (*trip.Itinerary, error) {
	ret := _m.Called(ctx, userID, tripID)

	if len(ret) == 0 {
		panic("no return value specified for GetItinerary")
	}

	var r0 *trip.Itinerary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*trip.Itinerary, error)); ok {
		return rf(ctx, userID, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *trip.Itinerary); ok {
		r0 = rf(ctx, userID, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Itinerary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetItinerary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItinerary'
type MockManager_GetItinerary_Call struct {
	*mock.Call
}

// GetItinerary is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tripID string
func (_e *MockManager_Expecter) GetItinerary(ctx interface{}, userID interface{}, tripID interface{}) *MockManager_GetItinerary_Call {
	return &MockManager_GetItinerary_Call{Call: _e.mock.On("GetItinerary", ctx, userID, tripID)}
}

func (_c *MockManager_GetItinerary_Call) Run(run func(ctx context.Context, userID string, tripID string)) *MockManager_GetItinerary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockManager_GetItinerary_Call) Return(_a0 *trip.Itinerary, _a1 error) *MockManager_GetItinerary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetItinerary_Call) RunAndReturn(run func(context.Context, string, string) (*trip.Itinerary, error)) *MockManager_GetItinerary_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, userID
func (_m *MockManager) List(ctx context.Context, userID string) ([]*trip.Trip, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*trip.Trip, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*trip.Trip); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockManager_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockManager_Expecter) List(ctx interface{}, userID interface{}) *MockManager_List_Call {
	return &MockManager_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockManager_List_Call) Run(run func(ctx context.Context, userID string)) *MockManager_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_List_Call) Return(_a0 []*trip.Trip, _a1 error) *MockManager_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_List_Call) RunAndReturn(run func(context.Context, string) ([]*trip.Trip, error)) *MockManager_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, userID, tripID, expectedVersion, title, description, status
func (_m *MockManager) Update(ctx context.Context, userID string, tripID string, expectedVersion int, title string, description *string, status string) (*trip.Trip, error) {
	ret := _m.Called(ctx, userID, tripID, expectedVersion, title, description, status)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string, *string, string) (*trip.Trip, error)); ok {
		return rf(ctx, userID, tripID, expectedVersion, title, description, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string, *string, string) *trip.Trip); ok {
		r0 = rf(ctx, userID, tripID, expectedVersion, title, description, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, string, *string, string) error); ok {
		r1 = rf(ctx, userID, tripID, expectedVersion, title, description, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockManager_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tripID string
//   - expectedVersion int
//   - title string
//   - description *string
//   - status string
func (_e *MockManager_Expecter) Update(ctx interface{}, userID interface{}, tripID interface{}, expectedVersion interface{}, title interface{}, description interface{}, status interface{}) *MockManager_Update_Call {
	return &MockManager_Update_Call{Call: _e.mock.On("Update", ctx, userID, tripID, expectedVersion, title, description, status)}
}

func (_c *MockManager_Update_Call) Run(run func(ctx context.Context, userID string, tripID string, expectedVersion int, title string, description *string, status string)) *MockManager_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(string), args[5].(*string), args[6].(string))
	})
	return _c
}

func (_c *MockManager_Update_Call) Return(_a0 *trip.Trip, _a1 error) *MockManager_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_Update_Call) RunAndReturn(run func(context.Context, string, string, int, string, *string, string) (*trip.Trip, error)) *MockManager_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
