// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package trip

import (
	context "context"

	trip "github.com/JosemaPereira/TrAIveler/backend/internal/trip"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateDestination provides a mock function with given fields: ctx, destination
func (_m *MockRepository) CreateDestination(ctx context.Context, destination *trip.Destination) error {
	ret := _m.Called(ctx, destination)

	if len(ret) == 0 {
		panic("no return value specified for CreateDestination")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Destination) error); ok {
		r0 = rf(ctx, destination)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateDestination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDestination'
type MockRepository_CreateDestination_Call struct {
	*mock.Call
}

// CreateDestination is a helper method to define mock.On call
//   - ctx context.Context
//   - destination *trip.Destination
func (_e *MockRepository_Expecter) CreateDestination(ctx interface{}, destination interface{}) *MockRepository_CreateDestination_Call {
	return &MockRepository_CreateDestination_Call{Call: _e.mock.On("CreateDestination", ctx, destination)}
}

func (_c *MockRepository_CreateDestination_Call) Run(run func(ctx context.Context, destination *trip.Destination)) *MockRepository_CreateDestination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.Destination))
	})
	return _c
}

func (_c *MockRepository_CreateDestination_Call) Return(_a0 error) *MockRepository_CreateDestination_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateDestination_Call) RunAndReturn(run func(context.Context, *trip.Destination) error) *MockRepository_CreateDestination_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTrip provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) CreateTrip(ctx context.Context, _a1 *trip.Trip) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateTrip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Trip) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTrip'
type MockRepository_CreateTrip_Call struct {
	*mock.Call
}

// CreateTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *trip.Trip
func (_e *MockRepository_Expecter) CreateTrip(ctx interface{}, _a1 interface{}) *MockRepository_CreateTrip_Call {
	return &MockRepository_CreateTrip_Call{Call: _e.mock.On("CreateTrip", ctx, _a1)}
}

func (_c *MockRepository_CreateTrip_Call) Run(run func(ctx context.Context, _a1 *trip.Trip)) *MockRepository_CreateTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.Trip))
	})
	return _c
}

func (_c *MockRepository_CreateTrip_Call) Return(_a0 error) *MockRepository_CreateTrip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateTrip_Call) RunAndReturn(run func(context.Context, *trip.Trip) error) *MockRepository_CreateTrip_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteActivity provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteActivity(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteActivity'
type MockRepository_DeleteActivity_Call struct {
	*mock.Call
}

// DeleteActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteActivity(ctx interface{}, id interface{}) *MockRepository_DeleteActivity_Call {
	return &MockRepository_DeleteActivity_Call{Call: _e.mock.On("DeleteActivity", ctx, id)}
}

func (_c *MockRepository_DeleteActivity_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteActivity_Call) Return(_a0 error) *MockRepository_DeleteActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteActivity_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteActivity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTrip provides a mock function with given fields: ctx, id
func (_m *MockRepository) DeleteTrip(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrip")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DeleteTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrip'
type MockRepository_DeleteTrip_Call struct {
	*mock.Call
}

// DeleteTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteTrip(ctx interface{}, id interface{}) *MockRepository_DeleteTrip_Call {
	return &MockRepository_DeleteTrip_Call{Call: _e.mock.On("DeleteTrip", ctx, id)}
}

func (_c *MockRepository_DeleteTrip_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_DeleteTrip_Call) Return(_a0 error) *MockRepository_DeleteTrip_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DeleteTrip_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_DeleteTrip_Call {
	_c.Call.Return(run)
	return _c
}

// FindTripByID provides a mock function with given fields: ctx, id
func (_m *MockRepository) FindTripByID(ctx context.Context, id string) (*trip.Trip, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindTripByID")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*trip.Trip, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *trip.Trip); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_FindTripByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTripByID'
type MockRepository_FindTripByID_Call struct {
	*mock.Call
}

// FindTripByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) FindTripByID(ctx interface{}, id interface{}) *MockRepository_FindTripByID_Call {
	return &MockRepository_FindTripByID_Call{Call: _e.mock.On("FindTripByID", ctx, id)}
}

func (_c *MockRepository_FindTripByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_FindTripByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_FindTripByID_Call) Return(_a0 *trip.Trip, _a1 error) *MockRepository_FindTripByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_FindTripByID_Call) RunAndReturn(run func(context.Context, string) (*trip.Trip, error)) *MockRepository_FindTripByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListTripsByUser provides a mock function with given fields: ctx, userID
func (_m *MockRepository) ListTripsByUser(ctx context.Context, userID string) ([]*trip.Trip, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListTripsByUser")
	}

	var r0 []*trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*trip.Trip, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*trip.Trip); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListTripsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTripsByUser'
type MockRepository_ListTripsByUser_Call struct {
	*mock.Call
}

// ListTripsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRepository_Expecter) ListTripsByUser(ctx interface{}, userID interface{}) *MockRepository_ListTripsByUser_Call {
	return &MockRepository_ListTripsByUser_Call{Call: _e.mock.On("ListTripsByUser", ctx, userID)}
}

func (_c *MockRepository_ListTripsByUser_Call) Run(run func(ctx context.Context, userID string)) *MockRepository_ListTripsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_ListTripsByUser_Call) Return(_a0 []*trip.Trip, _a1 error) *MockRepository_ListTripsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListTripsByUser_Call) RunAndReturn(run func(context.Context, string) ([]*trip.Trip, error)) *MockRepository_ListTripsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertActivity provides a mock function with given fields: ctx, activity
func (_m *MockRepository) UpsertActivity(ctx context.Context, activity *trip.Activity) error {
	ret := _m.Called(ctx, activity)

	if len(ret) == 0 {
		panic("no return value specified for UpsertActivity")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Activity) error); ok {
		r0 = rf(ctx, activity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpsertActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertActivity'
type MockRepository_UpsertActivity_Call struct {
	*mock.Call
}

// UpsertActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - activity *trip.Activity
func (_e *MockRepository_Expecter) UpsertActivity(ctx interface{}, activity interface{}) *MockRepository_UpsertActivity_Call {
	return &MockRepository_UpsertActivity_Call{Call: _e.mock.On("UpsertActivity", ctx, activity)}
}

func (_c *MockRepository_UpsertActivity_Call) Run(run func(ctx context.Context, activity *trip.Activity)) *MockRepository_UpsertActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.Activity))
	})
	return _c
}

func (_c *MockRepository_UpsertActivity_Call) Return(_a0 error) *MockRepository_UpsertActivity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpsertActivity_Call) RunAndReturn(run func(context.Context, *trip.Activity) error) *MockRepository_UpsertActivity_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertDay provides a mock function with given fields: ctx, day
func (_m *MockRepository) UpsertDay(ctx context.Context, day *trip.Day) error {
	ret := _m.Called(ctx, day)

	if len(ret) == 0 {
		panic("no return value specified for UpsertDay")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *trip.Day) error); ok {
		r0 = rf(ctx, day)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpsertDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertDay'
type MockRepository_UpsertDay_Call struct {
	*mock.Call
}

// UpsertDay is a helper method to define mock.On call
//   - ctx context.Context
//   - day *trip.Day
func (_e *MockRepository_Expecter) UpsertDay(ctx interface{}, day interface{}) *MockRepository_UpsertDay_Call {
	return &MockRepository_UpsertDay_Call{Call: _e.mock.On("UpsertDay", ctx, day)}
}

func (_c *MockRepository_UpsertDay_Call) Run(run func(ctx context.Context, day *trip.Day)) *MockRepository_UpsertDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*trip.Day))
	})
	return _c
}

func (_c *MockRepository_UpsertDay_Call) Return(_a0 error) *MockRepository_UpsertDay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpsertDay_Call) RunAndReturn(run func(context.Context, *trip.Day) error) *MockRepository_UpsertDay_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
