// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package conversation

import (
	context "context"

	ai "github.com/JosemaPereira/TrAIveler/backend/internal/ai"

	mock "github.com/stretchr/testify/mock"
)

// MockItineraryGenerator is an autogenerated mock type for the ItineraryGenerator type
type MockItineraryGenerator struct {
	mock.Mock
}

type MockItineraryGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItineraryGenerator) EXPECT() *MockItineraryGenerator_Expecter {
	return &MockItineraryGenerator_Expecter{mock: &_m.Mock}
}

// Continue provides a mock function with given fields: ctx, tripID, history
func (_m *MockItineraryGenerator) Continue(ctx context.Context, tripID string, history []ai.Message) (string, bool, error) {
	ret := _m.Called(ctx, tripID, history)

	if len(ret) == 0 {
		panic("no return value specified for Continue")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []ai.Message) (string, bool, error)); ok {
		return rf(ctx, tripID, history)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []ai.Message) string); ok {
		r0 = rf(ctx, tripID, history)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []ai.Message) bool); ok {
		r1 = rf(ctx, tripID, history)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, []ai.Message) error); ok {
		r2 = rf(ctx, tripID, history)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockItineraryGenerator_Continue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Continue'
type MockItineraryGenerator_Continue_Call struct {
	*mock.Call
}

// Continue is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - history []ai.Message
func (_e *MockItineraryGenerator_Expecter) Continue(ctx interface{}, tripID interface{}, history interface{}) *MockItineraryGenerator_Continue_Call {
	return &MockItineraryGenerator_Continue_Call{Call: _e.mock.On("Continue", ctx, tripID, history)}
}

func (_c *MockItineraryGenerator_Continue_Call) Run(run func(ctx context.Context, tripID string, history []ai.Message)) *MockItineraryGenerator_Continue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]ai.Message))
	})
	return _c
}

func (_c *MockItineraryGenerator_Continue_Call) Return(reply string, ready bool, err error) *MockItineraryGenerator_Continue_Call {
	_c.Call.Return(reply, ready, err)
	return _c
}

func (_c *MockItineraryGenerator_Continue_Call) RunAndReturn(run func(context.Context, string, []ai.Message) (string, bool, error)) *MockItineraryGenerator_Continue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockItineraryGenerator creates a new instance of MockItineraryGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItineraryGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItineraryGenerator {
	mock := &MockItineraryGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
