// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package conversation

import (
	context "context"

	conversation "github.com/JosemaPereira/TrAIveler/backend/internal/conversation"
	mock "github.com/stretchr/testify/mock"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// GetHistory provides a mock function with given fields: ctx, tripID
func (_m *MockManager) GetHistory(ctx context.Context, tripID string) (*conversation.Session, []*conversation.Message, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 *conversation.Session
	var r1 []*conversation.Message
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*conversation.Session, []*conversation.Message, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *conversation.Session); ok {
		r0 = rf(ctx, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conversation.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) []*conversation.Message); ok {
		r1 = rf(ctx, tripID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]*conversation.Message)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, tripID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockManager_GetHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistory'
type MockManager_GetHistory_Call struct {
	*mock.Call
}

// GetHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockManager_Expecter) GetHistory(ctx interface{}, tripID interface{}) *MockManager_GetHistory_Call {
	return &MockManager_GetHistory_Call{Call: _e.mock.On("GetHistory", ctx, tripID)}
}

func (_c *MockManager_GetHistory_Call) Run(run func(ctx context.Context, tripID string)) *MockManager_GetHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_GetHistory_Call) Return(_a0 *conversation.Session, _a1 []*conversation.Message, _a2 error) *MockManager_GetHistory_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockManager_GetHistory_Call) RunAndReturn(run func(context.Context, string) (*conversation.Session, []*conversation.Message, error)) *MockManager_GetHistory_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, tripID, content
func (_m *MockManager) SendMessage(ctx context.Context, tripID string, content string) (*conversation.Message, bool, error) {
	ret := _m.Called(ctx, tripID, content)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *conversation.Message
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*conversation.Message, bool, error)); ok {
		return rf(ctx, tripID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *conversation.Message); ok {
		r0 = rf(ctx, tripID, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conversation.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, tripID, content)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, tripID, content)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockManager_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockManager_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
//   - content string
func (_e *MockManager_Expecter) SendMessage(ctx interface{}, tripID interface{}, content interface{}) *MockManager_SendMessage_Call {
	return &MockManager_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, tripID, content)}
}

func (_c *MockManager_SendMessage_Call) Run(run func(ctx context.Context, tripID string, content string)) *MockManager_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockManager_SendMessage_Call) Return(_a0 *conversation.Message, _a1 bool, _a2 error) *MockManager_SendMessage_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockManager_SendMessage_Call) RunAndReturn(run func(context.Context, string, string) (*conversation.Message, bool, error)) *MockManager_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
