// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package conversation

import (
	context "context"

	conversation "github.com/JosemaPereira/TrAIveler/backend/internal/conversation"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AppendMessage provides a mock function with given fields: ctx, message
func (_m *MockRepository) AppendMessage(ctx context.Context, message *conversation.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for AppendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *conversation.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AppendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendMessage'
type MockRepository_AppendMessage_Call struct {
	*mock.Call
}

// AppendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *conversation.Message
func (_e *MockRepository_Expecter) AppendMessage(ctx interface{}, message interface{}) *MockRepository_AppendMessage_Call {
	return &MockRepository_AppendMessage_Call{Call: _e.mock.On("AppendMessage", ctx, message)}
}

func (_c *MockRepository_AppendMessage_Call) Run(run func(ctx context.Context, message *conversation.Message)) *MockRepository_AppendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*conversation.Message))
	})
	return _c
}

func (_c *MockRepository_AppendMessage_Call) Return(_a0 error) *MockRepository_AppendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AppendMessage_Call) RunAndReturn(run func(context.Context, *conversation.Message) error) *MockRepository_AppendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function with given fields: ctx, session
func (_m *MockRepository) CreateSession(ctx context.Context, session *conversation.Session) error {
	ret := _m.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *conversation.Session) error); ok {
		r0 = rf(ctx, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - session *conversation.Session
func (_e *MockRepository_Expecter) CreateSession(ctx interface{}, session interface{}) *MockRepository_CreateSession_Call {
	return &MockRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, session)}
}

func (_c *MockRepository_CreateSession_Call) Run(run func(ctx context.Context, session *conversation.Session)) *MockRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*conversation.Session))
	})
	return _c
}

func (_c *MockRepository_CreateSession_Call) Return(_a0 error) *MockRepository_CreateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateSession_Call) RunAndReturn(run func(context.Context, *conversation.Session) error) *MockRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionByTrip provides a mock function with given fields: ctx, tripID
func (_m *MockRepository) GetSessionByTrip(ctx context.Context, tripID string) (*conversation.Session, error) {
	ret := _m.Called(ctx, tripID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionByTrip")
	}

	var r0 *conversation.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*conversation.Session, error)); ok {
		return rf(ctx, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *conversation.Session); ok {
		r0 = rf(ctx, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conversation.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSessionByTrip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionByTrip'
type MockRepository_GetSessionByTrip_Call struct {
	*mock.Call
}

// GetSessionByTrip is a helper method to define mock.On call
//   - ctx context.Context
//   - tripID string
func (_e *MockRepository_Expecter) GetSessionByTrip(ctx interface{}, tripID interface{}) *MockRepository_GetSessionByTrip_Call {
	return &MockRepository_GetSessionByTrip_Call{Call: _e.mock.On("GetSessionByTrip", ctx, tripID)}
}

func (_c *MockRepository_GetSessionByTrip_Call) Run(run func(ctx context.Context, tripID string)) *MockRepository_GetSessionByTrip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_GetSessionByTrip_Call) Return(_a0 *conversation.Session, _a1 error) *MockRepository_GetSessionByTrip_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSessionByTrip_Call) RunAndReturn(run func(context.Context, string) (*conversation.Session, error)) *MockRepository_GetSessionByTrip_Call {
	_c.Call.Return(run)
	return _c
}

// ListMessages provides a mock function with given fields: ctx, sessionID
func (_m *MockRepository) ListMessages(ctx context.Context, sessionID string) ([]*conversation.Message, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for ListMessages")
	}

	var r0 []*conversation.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*conversation.Message, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*conversation.Message); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*conversation.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMessages'
type MockRepository_ListMessages_Call struct {
	*mock.Call
}

// ListMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockRepository_Expecter) ListMessages(ctx interface{}, sessionID interface{}) *MockRepository_ListMessages_Call {
	return &MockRepository_ListMessages_Call{Call: _e.mock.On("ListMessages", ctx, sessionID)}
}

func (_c *MockRepository_ListMessages_Call) Run(run func(ctx context.Context, sessionID string)) *MockRepository_ListMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_ListMessages_Call) Return(_a0 []*conversation.Message, _a1 error) *MockRepository_ListMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListMessages_Call) RunAndReturn(run func(context.Context, string) ([]*conversation.Message, error)) *MockRepository_ListMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
