// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package conversation

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	trip "github.com/JosemaPereira/TrAIveler/backend/internal/trip"
)

// MockTripAccess is an autogenerated mock type for the TripAccess type
type MockTripAccess struct {
	mock.Mock
}

type MockTripAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTripAccess) EXPECT() *MockTripAccess_Expecter {
	return &MockTripAccess_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, userID, tripID
func (_m *MockTripAccess) Get(ctx context.Context, userID string, tripID string) (*trip.Trip, error) {
	ret := _m.Called(ctx, userID, tripID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *trip.Trip
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*trip.Trip, error)); ok {
		return rf(ctx, userID, tripID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *trip.Trip); ok {
		r0 = rf(ctx, userID, tripID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trip.Trip)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, tripID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTripAccess_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTripAccess_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - tripID string
func (_e *MockTripAccess_Expecter) Get(ctx interface{}, userID interface{}, tripID interface{}) *MockTripAccess_Get_Call {
	return &MockTripAccess_Get_Call{Call: _e.mock.On("Get", ctx, userID, tripID)}
}

func (_c *MockTripAccess_Get_Call) Run(run func(ctx context.Context, userID string, tripID string)) *MockTripAccess_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTripAccess_Get_Call) Return(_a0 *trip.Trip, _a1 error) *MockTripAccess_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTripAccess_Get_Call) RunAndReturn(run func(context.Context, string, string) (*trip.Trip, error)) *MockTripAccess_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTripAccess creates a new instance of MockTripAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTripAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTripAccess {
	mock := &MockTripAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
