// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package auth

import (
	context "context"

	auth "github.com/JosemaPereira/TrAIveler/backend/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// CurrentUser provides a mock function with given fields: ctx, userID
func (_m *MockAccountService) CurrentUser(ctx context.Context, userID string) (*auth.CurrentUserResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CurrentUser")
	}

	var r0 *auth.CurrentUserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.CurrentUserResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.CurrentUserResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.CurrentUserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_CurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentUser'
type MockAccountService_CurrentUser_Call struct {
	*mock.Call
}

// CurrentUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAccountService_Expecter) CurrentUser(ctx interface{}, userID interface{}) *MockAccountService_CurrentUser_Call {
	return &MockAccountService_CurrentUser_Call{Call: _e.mock.On("CurrentUser", ctx, userID)}
}

func (_c *MockAccountService_CurrentUser_Call) Run(run func(ctx context.Context, userID string)) *MockAccountService_CurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAccountService_CurrentUser_Call) Return(_a0 *auth.CurrentUserResponse, _a1 error) *MockAccountService_CurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_CurrentUser_Call) RunAndReturn(run func(context.Context, string) (*auth.CurrentUserResponse, error)) *MockAccountService_CurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, req, ipAddress, userAgent
func (_m *MockAccountService) Login(ctx context.Context, req auth.LoginRequest, ipAddress string, userAgent string) (*auth.LoginResponse, error) {
	ret := _m.Called(ctx, req, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginRequest, string, string) (*auth.LoginResponse, error)); ok {
		return rf(ctx, req, ipAddress, userAgent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.LoginRequest, string, string) *auth.LoginResponse); ok {
		r0 = rf(ctx, req, ipAddress, userAgent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.LoginRequest, string, string) error); ok {
		r1 = rf(ctx, req, ipAddress, userAgent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAccountService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.LoginRequest
//   - ipAddress string
//   - userAgent string
func (_e *MockAccountService_Expecter) Login(ctx interface{}, req interface{}, ipAddress interface{}, userAgent interface{}) *MockAccountService_Login_Call {
	return &MockAccountService_Login_Call{Call: _e.mock.On("Login", ctx, req, ipAddress, userAgent)}
}

func (_c *MockAccountService_Login_Call) Run(run func(ctx context.Context, req auth.LoginRequest, ipAddress string, userAgent string)) *MockAccountService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.LoginRequest), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAccountService_Login_Call) Return(_a0 *auth.LoginResponse, _a1 error) *MockAccountService_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_Login_Call) RunAndReturn(run func(context.Context, auth.LoginRequest, string, string) (*auth.LoginResponse, error)) *MockAccountService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, req
func (_m *MockAccountService) Register(ctx context.Context, req auth.RegisterRequest) (*auth.RegisterResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.RegisterRequest) (*auth.RegisterResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.RegisterRequest) *auth.RegisterResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.RegisterRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAccountService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - req auth.RegisterRequest
func (_e *MockAccountService_Expecter) Register(ctx interface{}, req interface{}) *MockAccountService_Register_Call {
	return &MockAccountService_Register_Call{Call: _e.mock.On("Register", ctx, req)}
}

func (_c *MockAccountService_Register_Call) Run(run func(ctx context.Context, req auth.RegisterRequest)) *MockAccountService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.RegisterRequest))
	})
	return _c
}

func (_c *MockAccountService_Register_Call) Return(_a0 *auth.RegisterResponse, _a1 error) *MockAccountService_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountService_Register_Call) RunAndReturn(run func(context.Context, auth.RegisterRequest) (*auth.RegisterResponse, error)) *MockAccountService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
