// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package auth

import (
	context "context"

	auth "github.com/JosemaPereira/TrAIveler/backend/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockRefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type MockRefreshTokenRepository struct {
	mock.Mock
}

type MockRefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenRepository) EXPECT() *MockRefreshTokenRepository_Expecter {
	return &MockRefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockRefreshTokenRepository) CreateRefreshToken(ctx context.Context, token *auth.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockRefreshTokenRepository_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.RefreshToken
func (_e *MockRefreshTokenRepository_Expecter) CreateRefreshToken(ctx interface{}, token interface{}) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	return &MockRefreshTokenRepository_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, token)}
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) Run(run func(ctx context.Context, token *auth.RefreshToken)) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.RefreshToken))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) Return(_a0 error) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_CreateRefreshToken_Call) RunAndReturn(run func(context.Context, *auth.RefreshToken) error) *MockRefreshTokenRepository_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshTokenByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockRefreshTokenRepository) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (*auth.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshTokenByHash")
	}

	var r0 *auth.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRefreshTokenRepository_GetRefreshTokenByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshTokenByHash'
type MockRefreshTokenRepository_GetRefreshTokenByHash_Call struct {
	*mock.Call
}

// GetRefreshTokenByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockRefreshTokenRepository_Expecter) GetRefreshTokenByHash(ctx interface{}, tokenHash interface{}) *MockRefreshTokenRepository_GetRefreshTokenByHash_Call {
	return &MockRefreshTokenRepository_GetRefreshTokenByHash_Call{Call: _e.mock.On("GetRefreshTokenByHash", ctx, tokenHash)}
}

func (_c *MockRefreshTokenRepository_GetRefreshTokenByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockRefreshTokenRepository_GetRefreshTokenByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_GetRefreshTokenByHash_Call) Return(_a0 *auth.RefreshToken, _a1 error) *MockRefreshTokenRepository_GetRefreshTokenByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRefreshTokenRepository_GetRefreshTokenByHash_Call) RunAndReturn(run func(context.Context, string) (*auth.RefreshToken, error)) *MockRefreshTokenRepository_GetRefreshTokenByHash_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllRefreshTokens provides a mock function with given fields: ctx, userID
func (_m *MockRefreshTokenRepository) RevokeAllRefreshTokens(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllRefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeAllRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllRefreshTokens'
type MockRefreshTokenRepository_RevokeAllRefreshTokens_Call struct {
	*mock.Call
}

// RevokeAllRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockRefreshTokenRepository_Expecter) RevokeAllRefreshTokens(ctx interface{}, userID interface{}) *MockRefreshTokenRepository_RevokeAllRefreshTokens_Call {
	return &MockRefreshTokenRepository_RevokeAllRefreshTokens_Call{Call: _e.mock.On("RevokeAllRefreshTokens", ctx, userID)}
}

func (_c *MockRefreshTokenRepository_RevokeAllRefreshTokens_Call) Run(run func(ctx context.Context, userID string)) *MockRefreshTokenRepository_RevokeAllRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllRefreshTokens_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeAllRefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeAllRefreshTokens_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_RevokeAllRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, id
func (_m *MockRefreshTokenRepository) RevokeRefreshToken(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRefreshTokenRepository_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockRefreshTokenRepository_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRefreshTokenRepository_Expecter) RevokeRefreshToken(ctx interface{}, id interface{}) *MockRefreshTokenRepository_RevokeRefreshToken_Call {
	return &MockRefreshTokenRepository_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, id)}
}

func (_c *MockRefreshTokenRepository_RevokeRefreshToken_Call) Run(run func(ctx context.Context, id string)) *MockRefreshTokenRepository_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeRefreshToken_Call) Return(_a0 error) *MockRefreshTokenRepository_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRefreshTokenRepository_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockRefreshTokenRepository_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRefreshTokenRepository creates a new instance of MockRefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenRepository {
	mock := &MockRefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
