// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package auth

import (
	context "context"

	subscription "github.com/JosemaPereira/TrAIveler/backend/internal/subscription"
	mock "github.com/stretchr/testify/mock"
)

// MocksubscriptionCreator is an autogenerated mock type for the subscriptionCreator type
type MocksubscriptionCreator struct {
	mock.Mock
}

type MocksubscriptionCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MocksubscriptionCreator) EXPECT() *MocksubscriptionCreator_Expecter {
	return &MocksubscriptionCreator_Expecter{mock: &_m.Mock}
}

// CreateSubscription provides a mock function with given fields: ctx, userID, planID, token
func (_m *MocksubscriptionCreator) CreateSubscription(ctx context.Context, userID string, planID string, token string) (*subscription.Subscription, error) {
	ret := _m.Called(ctx, userID, planID, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 *subscription.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*subscription.Subscription, error)); ok {
		return rf(ctx, userID, planID, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *subscription.Subscription); ok {
		r0 = rf(ctx, userID, planID, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*subscription.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, planID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MocksubscriptionCreator_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MocksubscriptionCreator_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - planID string
//   - token string
func (_e *MocksubscriptionCreator_Expecter) CreateSubscription(ctx interface{}, userID interface{}, planID interface{}, token interface{}) *MocksubscriptionCreator_CreateSubscription_Call {
	return &MocksubscriptionCreator_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctx, userID, planID, token)}
}

func (_c *MocksubscriptionCreator_CreateSubscription_Call) Run(run func(ctx context.Context, userID string, planID string, token string)) *MocksubscriptionCreator_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MocksubscriptionCreator_CreateSubscription_Call) Return(_a0 *subscription.Subscription, _a1 error) *MocksubscriptionCreator_CreateSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MocksubscriptionCreator_CreateSubscription_Call) RunAndReturn(run func(context.Context, string, string, string) (*subscription.Subscription, error)) *MocksubscriptionCreator_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocksubscriptionCreator creates a new instance of MocksubscriptionCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocksubscriptionCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocksubscriptionCreator {
	mock := &MocksubscriptionCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
