// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package auth

import (
	context "context"

	auth "github.com/JosemaPereira/TrAIveler/backend/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenRefresher is an autogenerated mock type for the TokenRefresher type
type MockTokenRefresher struct {
	mock.Mock
}

type MockTokenRefresher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRefresher) EXPECT() *MockTokenRefresher_Expecter {
	return &MockTokenRefresher_Expecter{mock: &_m.Mock}
}

// RefreshToken provides a mock function with given fields: ctx, rawRefreshToken
func (_m *MockTokenRefresher) RefreshToken(ctx context.Context, rawRefreshToken string) (auth.TokenPair, error) {
	ret := _m.Called(ctx, rawRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 auth.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (auth.TokenPair, error)); ok {
		return rf(ctx, rawRefreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) auth.TokenPair); ok {
		r0 = rf(ctx, rawRefreshToken)
	} else {
		r0 = ret.Get(0).(auth.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawRefreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRefresher_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type MockTokenRefresher_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - rawRefreshToken string
func (_e *MockTokenRefresher_Expecter) RefreshToken(ctx interface{}, rawRefreshToken interface{}) *MockTokenRefresher_RefreshToken_Call {
	return &MockTokenRefresher_RefreshToken_Call{Call: _e.mock.On("RefreshToken", ctx, rawRefreshToken)}
}

func (_c *MockTokenRefresher_RefreshToken_Call) Run(run func(ctx context.Context, rawRefreshToken string)) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRefresher_RefreshToken_Call) Return(_a0 auth.TokenPair, _a1 error) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRefresher_RefreshToken_Call) RunAndReturn(run func(context.Context, string) (auth.TokenPair, error)) *MockTokenRefresher_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRefresher creates a new instance of MockTokenRefresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRefresher {
	mock := &MockTokenRefresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
