// Code generated by mockery v2.53.6. DO NOT EDIT.

//go:build test

package auth

import (
	context "context"

	auth "github.com/JosemaPereira/TrAIveler/backend/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenIssuer is an autogenerated mock type for the TokenIssuer type
type MockTokenIssuer struct {
	mock.Mock
}

type MockTokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenIssuer) EXPECT() *MockTokenIssuer_Expecter {
	return &MockTokenIssuer_Expecter{mock: &_m.Mock}
}

// IssueTokens provides a mock function with given fields: ctx, userID, hasSubscription
func (_m *MockTokenIssuer) IssueTokens(ctx context.Context, userID string, hasSubscription bool) (auth.TokenPair, error) {
	ret := _m.Called(ctx, userID, hasSubscription)

	if len(ret) == 0 {
		panic("no return value specified for IssueTokens")
	}

	var r0 auth.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (auth.TokenPair, error)); ok {
		return rf(ctx, userID, hasSubscription)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) auth.TokenPair); ok {
		r0 = rf(ctx, userID, hasSubscription)
	} else {
		r0 = ret.Get(0).(auth.TokenPair)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, userID, hasSubscription)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenIssuer_IssueTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IssueTokens'
type MockTokenIssuer_IssueTokens_Call struct {
	*mock.Call
}

// IssueTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - hasSubscription bool
func (_e *MockTokenIssuer_Expecter) IssueTokens(ctx interface{}, userID interface{}, hasSubscription interface{}) *MockTokenIssuer_IssueTokens_Call {
	return &MockTokenIssuer_IssueTokens_Call{Call: _e.mock.On("IssueTokens", ctx, userID, hasSubscription)}
}

func (_c *MockTokenIssuer_IssueTokens_Call) Run(run func(ctx context.Context, userID string, hasSubscription bool)) *MockTokenIssuer_IssueTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockTokenIssuer_IssueTokens_Call) Return(_a0 auth.TokenPair, _a1 error) *MockTokenIssuer_IssueTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenIssuer_IssueTokens_Call) RunAndReturn(run func(context.Context, string, bool) (auth.TokenPair, error)) *MockTokenIssuer_IssueTokens_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenIssuer creates a new instance of MockTokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenIssuer {
	mock := &MockTokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
